### ISSUE TITLE
Can not find the data/train-clean-360-asv/pitch.scp

### ISSUE THREAD

**Issue by yaoxunji** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#10]
Hi, I encountered a problem when running _run.sh step 10_, that the downloaded train-clean-360-spk.tar.gz does not contain pitch.scp, where can I solve the problem?
![1648607798(1)](https://user-images.githubusercontent.com/17915763/160739706-8f4dd02c-04d2-4786-9854-fa8216568614.png)

**Comment by Natalia-T** [comment]
Hi @yaoxunji. 
Thank you for reporting the issue!
It is fixed in https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/commit/475ad51fbc212701dc71afa69d9a872e35d5e31f
(to continue from the same stage: 
`run.sh:  stage=10`
`anonymize_data_dir.sh:  stage=4`
`make_netcdf.sh:  stage=2`)

**Comment by Natalia-T** [comment]
Hi @yaoxunji.
Thank you for reporting the issue!
It is fixed in https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/commit/53eccc0938c07836ac8d992fa6ff467ab15448eb
(to continue from the same stage:
run.sh: stage=10
anonymize_data_dir.sh: stage=4
make_netcdf.sh: stage=2)
