### ISSUE TITLE
configure failed: MKL libraries could not be found. Please use the switch --mkl-libdir or try another math library, e.g. --mathlib=ATLAS (would be slower) 

### ISSUE THREAD

**Issue by RMobina** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#20]
I am currently experiencing some problems, and I hope to get your reply.
I encountered the problem as shown below when I was running install.sh, and it couldn't proceed.
I also checked the https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/issues/12, but still, have the current issue.
I'm using Ubuntu 20.04.4 and cuda 11.2

Building Kaldi src
Configuring KALDI to use MKL.
Checking compiler g++ ...
Checking OpenFst library in /home/Voice-Privacy-Challenge-2022/kaldi/tools/openfst-1.6.7 ...
Checking cub library in /home/Voice-Privacy-Challenge-2022/kaldi/tools/cub-1.8.0 ...
Doing OS specific configurations ...
On Linux: Checking for linear algebra header files ...
Configuring MKL library directory: ***configure failed: MKL libraries could not be found. Please use the switch --mkl-libdir or try another math library, e.g. --mathlib=ATLAS (would be slower) ***

**Comment by Natalia-T** [comment]
If you do not have MKL, you should install it using the following script: https://github.com/kaldi-asr/kaldi/blob/master/tools/extras/install_mkl.sh. To install MKL you will need root privileges. 

Otherwise, if you already have the installed MKL in your system, you should add parameter `--mkl-root=DIR` when call `configure`:
https://github.com/kaldi-asr/kaldi/blob/d673298886e8d62d4c890e5e3eac8491df0b7e12/src/configure#L89

If you do not have neither MKL, nor `sudo` rights, you can try to use `singularity` if it is installed in the system (https://sylabs.io/guides/latest/user-guide/).

Also, there should be a way to install MKL with `pip`: https://www.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-using-package-managers/pip.html (though I have not tried this option)

**Comment by RMobina** [comment]
Thank you @Natalia-T  for your reply. It worked
